# NOTE:
You cannot run this part by part because this is a live code and will end up doing wacky stuff. Run it at once all the way through

This is the import in order to import the code needed. if you use as you can just shorten the name basically 

In [13]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

import colorama
from colorama import Fore

This will define the object that is the camera, 0 means built in, it could also possibly be -1.

The reason I have camera setting equal to zero and have it deleted is because Jpnotebook will make camera an index if I don't delete it before hand. 

In [14]:
camera = [0]
del camera
camera = cv.VideoCapture(0)

This checks if the Camera is open, make sure that you run this part all at once or the whole thing will not work step by step

In [15]:
if not camera.isOpened():
    print(Fore.RED + '\033[1m' + 'Da Camera is broken' + '\033[0m')
    
elif  camera.isOpened():
    print(Fore.GREEN + '\033[1m' + 'The Camera is Open' + '\033[0m')
    
    

The Camera is Open


We know use .read to get the webcam footage. The first variable is just a boolean that basically checks if the camera or video stream is uninterupted, while the img is the frame.


In [16]:

stream, img = camera.read()
if stream == True: 
    print(Fore.GREEN + '\033[1m' + 'The stream is operational' + '\033[0m')

The stream is operational


Below uses imshow, the first line is the name of the opened window, the second is the actual image you want to show.

using waitKey(0) means it will pause UNTIL something is pressed. If you put a number it works in miliseconds

In [17]:
#cv.imshow("LIVESTREAM",img)

#This waits for a keystroke
#cv.waitKey(0) 
  
#closing all open windows 
#cv.destroyAllWindows() 

Now we will actually fully continue to show an entire video. and wait for a user input. 

In [18]:
while True:
    stream, img = camera.read()
    cv.imshow("LIVESTREAM",img)
    
    #This converts it to a grey scaled image and displays it COLOR_RGB2GRAY
    greyscaled = cv.cvtColor(img, cv.COLOR_RGB2GRAY)
    cv.imshow("GreyLive",greyscaled)
    
    cntr = (-100,-100)
    color = (255, 0, 0)
    cv.circle(img=greyscaled, center = (200,300), radius =50, color =(255,0,0), thickness=10)

    cv.imshow("circlehope",greyscaled)
    
    
    
    
   #wait key returns the key that is pressed and records it, The reason you need the &0xFF is because 
   #waitKey exports binary with a bunch of garbage in the front of it. 0xFF is basically just a constant, and & 
   #is a built in function that goes number by number and manipulates it. 
   #This basically means that key is the pressed key without any junk.
   #If I did waitKey(0) it would stop on a solid image until I put an input. 
   #While if I make it a 1 it will stop shortly then continue.
    key  = cv.waitKey(1) & 0xFF
    
    #now we will compare that to the desired key of input, we use ord to conver a letter into its ASCII code 
    #which key is in. if it is that we will then break out of the loop
    
    if key == ord(' '):
        break
    
# After the loop release the cap object
camera.release()
# Destroy all the windows
cv.destroyAllWindows()
print(greyscaled)
    

[[11 11 10 ... 15 14 14]
 [11 11 11 ... 13 13 13]
 [11 11 11 ... 12 13 13]
 ...
 [12 12 12 ... 14 14 14]
 [13 13 12 ... 13 11 11]
 [12 13 12 ... 13 13 12]]


# list of useful links 

https://www.geeksforgeeks.org/python-opencv-capture-video-from-camera/
https://docs.opencv.org/4.x/dd/d43/tutorial_py_video_display.html
https://www.geeksforgeeks.org/check-if-the-camera-is-opened-or-not-using-opencv-python/
https://learnopencv.com/reading-and-writing-videos-using-opencv/
